# config/packages/security.yaml
security:
    # 1) Hashing des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2) Chargement des utilisateurs
    providers:
        users_in_memory:
            memory: null
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # 3) Firewalls
    firewalls:
        # Désactivation de la sécurité pour les assets et le profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Point d’entrée login (stateless, JSON)
        login:
            pattern:  ^/login$
            stateless: true
            provider: app_user_provider
            json_login:
                check_path:      /login
                username_path:   email
                password_path:   password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                # success_handler / failure_handler (facultatif)

        google_oauth:
            pattern: ^/connect/google        
            stateless: true
            custom_authenticators:
                - App\Security\GoogleAuthenticator 

        # Toutes les routes /api sont protégées par JWT
        api:
            pattern:   ^/api
            stateless: true
            provider:  app_user_provider   # ← ajoute ceci
            jwt: ~
            # si tu veux des cookies HttpOnly à la place des headers :
            # jwt_cookie: true
      

    # 4) Contrôles d’accès
    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/api,     roles: IS_AUTHENTICATED_FULLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

# --------------------------------------------------
# Configuration spécifique pour les tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm:    auto
                cost:         4   # bcrypt minimal
                time_cost:    3   # argon2 minimal
                memory_cost: 10   # argon2 minimal
