doctrine:
    dbal:
        default_connection: lacryo_genius_alm
        connections:
            lacryo_genius_alm:
                url: '%env(resolve:DATABASE_URL_LACRYO_GENIUS_ALM)%'

    orm:
        default_entity_manager: lacryo_genius_alm
        entity_managers:
            lacryo_genius_alm:
                connection: lacryo_genius_alm
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/LacryoGeniusAlm'
                        prefix: 'App\Entity\LacryoGeniusAlm'
                        alias: LacryoGeniusAlm